// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppConfig struct {
	ID        pgtype.UUID        `json:"id"`
	AppName   string             `json:"app_name"`
	Endpoint  string             `json:"endpoint"`
	Configs   []byte             `json:"configs"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OauthConfig struct {
	ID           pgtype.UUID        `json:"id"`
	Key          string             `json:"key"`
	ClientSecret string             `json:"client_secret"`
	Endpoint     string             `json:"endpoint"`
	UserID       pgtype.UUID        `json:"user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID               pgtype.UUID        `json:"id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Password         pgtype.Text        `json:"password"`
	GithubProviderID pgtype.Text        `json:"github_provider_id"`
	GoogleProviderID pgtype.Text        `json:"google_provider_id"`
	Type             string             `json:"type"`
	Avatar           pgtype.Text        `json:"avatar"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
