// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chekidConfigExist = `-- name: ChekidConfigExist :one
SELECT id from oauth_configs WHERE key=$1 and user_id=$2
`

type ChekidConfigExistParams struct {
	Key    string      `json:"key"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChekidConfigExist(ctx context.Context, arg ChekidConfigExistParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, chekidConfigExist, arg.Key, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createAppConfig = `-- name: CreateAppConfig :one
INSERT INTO app_configs (id,app_name ,endpoint,configs,user_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, app_name, endpoint, configs, user_id, created_at, updated_at
`

type CreateAppConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	AppName  string      `json:"app_name"`
	Endpoint string      `json:"endpoint"`
	Configs  []byte      `json:"configs"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateAppConfig(ctx context.Context, arg CreateAppConfigParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, createAppConfig,
		arg.ID,
		arg.AppName,
		arg.Endpoint,
		arg.Configs,
		arg.UserID,
	)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Endpoint,
		&i.Configs,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    id,
    username,
    email,
    password,
    github_provider_id,
    google_provider_id,
    avatar
)
VALUES (
    $1, $2, $3, $4, $5,$6,$7
)
RETURNING id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at
`

type CreateUserParams struct {
	ID               pgtype.UUID `json:"id"`
	Username         string      `json:"username"`
	Email            string      `json:"email"`
	Password         pgtype.Text `json:"password"`
	GithubProviderID pgtype.Text `json:"github_provider_id"`
	GoogleProviderID pgtype.Text `json:"google_provider_id"`
	Avatar           pgtype.Text `json:"avatar"`
}

// internal/db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.GithubProviderID,
		arg.GoogleProviderID,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creteOauthConfig = `-- name: CreteOauthConfig :one
INSERT INTO oauth_configs (id,key,endpoint,user_id) VALUES($1,$2,$3,$4) RETURNING id, key, endpoint, user_id, created_at, updated_at
`

type CreteOauthConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	Key      string      `json:"key"`
	Endpoint string      `json:"endpoint"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreteOauthConfig(ctx context.Context, arg CreteOauthConfigParams) (OauthConfig, error) {
	row := q.db.QueryRow(ctx, creteOauthConfig,
		arg.ID,
		arg.Key,
		arg.Endpoint,
		arg.UserID,
	)
	var i OauthConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Endpoint,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOauthConfig = `-- name: DeleteOauthConfig :exec
DELETE FROM oauth_configs WHERE id=$1 AND user_id=$2
`

type DeleteOauthConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteOauthConfig(ctx context.Context, arg DeleteOauthConfigParams) error {
	_, err := q.db.Exec(ctx, deleteOauthConfig, arg.ID, arg.UserID)
	return err
}

const getAppConfigByID = `-- name: GetAppConfigByID :one
SELECT id, app_name, endpoint, configs, user_id, created_at, updated_at FROM app_configs WHERE id = $1 AND user_id = $2
`

type GetAppConfigByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAppConfigByID(ctx context.Context, arg GetAppConfigByIDParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfigByID, arg.ID, arg.UserID)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Endpoint,
		&i.Configs,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppConfigs = `-- name: GetAppConfigs :many
SELECT id, app_name, endpoint, configs, user_id, created_at, updated_at FROM app_configs WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAppConfigs(ctx context.Context, userID pgtype.UUID) ([]AppConfig, error) {
	rows, err := q.db.Query(ctx, getAppConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppConfig
	for rows.Next() {
		var i AppConfig
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Endpoint,
			&i.Configs,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOauthConfigData = `-- name: GetOauthConfigData :one
SELECT id, key, endpoint, user_id, created_at, updated_at from oauth_configs WHERE id=$1
`

func (q *Queries) GetOauthConfigData(ctx context.Context, id pgtype.UUID) (OauthConfig, error) {
	row := q.db.QueryRow(ctx, getOauthConfigData, id)
	var i OauthConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Endpoint,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOauthList = `-- name: GetOauthList :many
SELECT id,key,endpoint,created_at,updated_at from oauth_configs where user_id=$1
`

type GetOauthListRow struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Endpoint  string             `json:"endpoint"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOauthList(ctx context.Context, userID pgtype.UUID) ([]GetOauthListRow, error) {
	rows, err := q.db.Query(ctx, getOauthList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOauthListRow
	for rows.Next() {
		var i GetOauthListRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Endpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGithubProviderID = `-- name: GetUserByGithubProviderID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at FROM users WHERE github_provider_id = $1
`

func (q *Queries) GetUserByGithubProviderID(ctx context.Context, githubProviderID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubProviderID, githubProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGithubProviderIDAndEmail = `-- name: GetUserByGithubProviderIDAndEmail :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at from users where github_provider_id = $1 AND email = $2
`

type GetUserByGithubProviderIDAndEmailParams struct {
	GithubProviderID pgtype.Text `json:"github_provider_id"`
	Email            string      `json:"email"`
}

func (q *Queries) GetUserByGithubProviderIDAndEmail(ctx context.Context, arg GetUserByGithubProviderIDAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubProviderIDAndEmail, arg.GithubProviderID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleProviderID = `-- name: GetUserByGoogleProviderID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at FROM users WHERE google_provider_id = $1
`

func (q *Queries) GetUserByGoogleProviderID(ctx context.Context, googleProviderID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleProviderID, googleProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserbyGoogleProviderIDAndEmail = `-- name: GetUserbyGoogleProviderIDAndEmail :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at from users where google_provider_id = $1 AND email = $2
`

type GetUserbyGoogleProviderIDAndEmailParams struct {
	GoogleProviderID pgtype.Text `json:"google_provider_id"`
	Email            string      `json:"email"`
}

func (q *Queries) GetUserbyGoogleProviderIDAndEmail(ctx context.Context, arg GetUserbyGoogleProviderIDAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserbyGoogleProviderIDAndEmail, arg.GoogleProviderID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.GithubProviderID,
			&i.GoogleProviderID,
			&i.Type,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppConfig = `-- name: UpdateAppConfig :one
UPDATE app_configs SET
    app_name = COALESCE($3, app_name),
    endpoint  = COALESCE($4, endpoint),
    configs   = COALESCE($5, configs)
WHERE id = $1 AND user_id = $2
RETURNING id, app_name, endpoint, configs, user_id, created_at, updated_at
`

type UpdateAppConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	AppName  string      `json:"app_name"`
	Endpoint string      `json:"endpoint"`
	Configs  []byte      `json:"configs"`
}

func (q *Queries) UpdateAppConfig(ctx context.Context, arg UpdateAppConfigParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, updateAppConfig,
		arg.ID,
		arg.UserID,
		arg.AppName,
		arg.Endpoint,
		arg.Configs,
	)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Endpoint,
		&i.Configs,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOauthConfig = `-- name: UpdateOauthConfig :one
UPDATE oauth_configs SET 
    endpoint = COALESCE($3, endpoint),
    key = COALESCE($4, key)
WHERE id=$1 AND user_id=$2 
RETURNING id, key, endpoint, user_id, created_at, updated_at
`

type UpdateOauthConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
	Key      string      `json:"key"`
}

func (q *Queries) UpdateOauthConfig(ctx context.Context, arg UpdateOauthConfigParams) (OauthConfig, error) {
	row := q.db.QueryRow(ctx, updateOauthConfig,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.Key,
	)
	var i OauthConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Endpoint,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
