// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    username,
    email,
    password,
    github_provider_id,
    google_provider_id,
    type,
    avatar
)
VALUES (
    $1, $2, $3, $4, $5, COALESCE($6, 'free'), $7
)
RETURNING id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username         string      `json:"username"`
	Email            string      `json:"email"`
	Password         pgtype.Text `json:"password"`
	GithubProviderID pgtype.Text `json:"github_provider_id"`
	GoogleProviderID pgtype.Text `json:"google_provider_id"`
	Column6          interface{} `json:"column_6"`
	Avatar           pgtype.Text `json:"avatar"`
}

// internal/db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.GithubProviderID,
		arg.GoogleProviderID,
		arg.Column6,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGithubProviderID = `-- name: GetUserByGithubProviderID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
FROM users
WHERE github_provider_id = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByGithubProviderID(ctx context.Context, githubProviderID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubProviderID, githubProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleProviderID = `-- name: GetUserByGoogleProviderID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
FROM users
WHERE google_provider_id = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByGoogleProviderID(ctx context.Context, googleProviderID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleProviderID, googleProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.GithubProviderID,
			&i.GoogleProviderID,
			&i.Type,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    password = COALESCE($4, password),
    github_provider_id = COALESCE($5, github_provider_id),
    google_provider_id = COALESCE($6, google_provider_id),
    type = COALESCE($7, type),
    avatar = COALESCE($8, avatar),
    updated_at = now()
WHERE id = $1
AND deleted_at IS NULL
RETURNING id, username, email, password, github_provider_id, google_provider_id, type, avatar, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID               pgtype.UUID `json:"id"`
	Username         string      `json:"username"`
	Email            string      `json:"email"`
	Password         pgtype.Text `json:"password"`
	GithubProviderID pgtype.Text `json:"github_provider_id"`
	GoogleProviderID pgtype.Text `json:"google_provider_id"`
	Type             string      `json:"type"`
	Avatar           pgtype.Text `json:"avatar"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.GithubProviderID,
		arg.GoogleProviderID,
		arg.Type,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.GithubProviderID,
		&i.GoogleProviderID,
		&i.Type,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
